export const signStatusResData = [
  { signDay: '第 1 天', icon: '/personal/static/images/icon_signed_in.png', status: '已签到' },
  { signDay: '第 2 天', icon: '/personal/static/images/icon_signed_in.png', status: '已签到' },
  { signDay: '第 3 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 4 天', icon: '/personal/static/images/icon_sign_gift.png', status: '+50' },
  { signDay: '第 5 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 6 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 7 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 8 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 9 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 10 天', icon: '/personal/static/images/icon_sign_gift.png', status: '+50' },
  { signDay: '第 11 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 12 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 13 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 14 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 15 天', icon: '/personal/static/images/icon_sign_gift.png', status: '+50' },
  { signDay: '第 16 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 17 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 18 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 19 天', icon: '/personal/static/images/icon_sign_coin.png', status: '+50' },
  { signDay: '第 20 天', icon: '/personal/static/images/icon_sign_gift.png', status: '+50' },
];
