export const consumChartResData = [
  {
    status: true,
    num: '0',
    starIconActive: '/personal/static/images/icon_star_lv1_active.png',
    starIconInActive: '/personal/static/images/icon_star_lv1_inactive.png',
    barBgActive: '/personal/static/images/bg_star_lv1_active.png',
    barBgInActive: '/personal/static/images/bg_star_lv1_inactive.png',
    type: '普通会员',
  },
  {
    status: true,
    num: '2000',
    starIconActive: '/personal/static/images/icon_star_lv2_active.png',
    starIconInActive: '/personal/static/images/icon_star_lv2_inactive.png',
    barBgActive: '/personal/static/images/bg_star_lv2_active.png',
    barBgInActive: '/personal/static/images/bg_star_lv2_inactive.png',
    type: '白银会员',
  },
  {
    status: false,
    num: '5000',
    starIconActive: '/personal/static/images/icon_star_lv3_active.png',
    starIconInActive: '/personal/static/images/icon_star_lv3_inactive.png',
    barBgActive: '/personal/static/images/bg_star_lv3_active.png',
    barBgInActive: '/personal/static/images/bg_star_lv3_inactive.png',
    type: '黄金会员',
  },
  {
    status: false,
    num: '8000',
    starIconActive: '/personal/static/images/icon_star_lv4_active.png',
    starIconInActive: '/personal/static/images/icon_star_lv4_inactive.png',
    barBgActive: '/personal/static/images/bg_star_lv4_active.png',
    barBgInActive: '/personal/static/images/bg_star_lv4_inactive.png',
    type: '铂金会员',
  },
  {
    status: false,
    num: '10000',
    starIconActive: '/personal/static/images/icon_star_lv5_active.png',
    starIconInActive: '/personal/static/images/icon_star_lv5_inactive.png',
    barBgActive: '/personal/static/images/bg_star_lv5_active.png',
    barBgInActive: '/personal/static/images/bg_star_lv5_inactive.png',
    type: '钻石会员',
  },
];
